version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/public/
    volumes:
      - ./public/:/var/www/public/
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.20
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
#      - "8443:443"
    volumes:
      - ./public/:/var/www/public/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./log/nginx:/var/log/nginx
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
